name: SARS2-mut-fitness
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - altair=4.2
  - biopython=1.79
  - black-jupyter
  - entrez-direct=16.2
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-comprehensions
  - flake8-import-order
  - flake8-nb
  - git-lfs
  - jupyter_contrib_nbextensions
  - jupyterlab
  - pandas=1.4
  - papermill=2.3.4
  - python=3.9
  - scikit-learn=1.1.1
  - snakemake=7.18.2
  - usher=0.5.6
