name: SARS2-mut-fitness
channels:
  - conda-forge
  - defaults
  - bioconda

dependencies:
  - altair=4.2
  - biopython=1.79
  - entrez-direct=16.2
  - git-lfs
  - jupyter_contrib_nbextensions
  - jupyterlab
  - markdown
  - matplotlib=3.6
  - openpyxl
  - pandas=1.4
  - papermill=2.3.4
  - python=3.9
  - scikit-learn=1.1.1
  - snakemake=7.18.2
  - usher=0.5.6
